---

repo_install: false

docker_packages:
  tools:
    compose:
      file: docker-compose-Linux-x86_64-v1.15.0
      url: https://github.com/docker/compose/releases/download/1.15.0/docker-compose-Linux-x86_64
    compose_sh:
      file: docker-compose-v1.15.0-run.sh
    machine:
      file: docker-machine-Linux-x86_64-v0.12.2
      url: https://github.com/docker/machine/releases/download/v0.12.2/docker-machine-Linux-x86_64


  docker_download_url: https://download.docker.com/linux/ubuntu/dists/
  version_expect: 1.13.1

  CentOS:
    _7:
      file: docker-engine-1.13.1-1.el7.centos.x86_64.rpm
      url: https://yum.dockerproject.org/repo/main/centos/7/Packages/docker-engine-1.13.1-1.el7.centos.x86_64.rpm

docker_group: docker
