---

- name: Setup proxy for package manager
  include: "proxy/{{ ansible_pkg_mgr }}.yml"

- name: Update repo
  include: "{{ item }}"
  with_first_found:
  - files:
    - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    # - 'default.yml'
    paths: '{{ role_path }}/tasks/os_aware'
    # skip: true

