---

- debug: msg={{ group_names }}
- debug: msg={{ hostvars[groups['bootstrap'][0]]['ansible_host'] }}
- debug: msg={{ groups['agents'] }}

- name: Disable sudo password prompts
  lineinfile:
    path: /etc/sudoers
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    insertafter: '## Same thing without a password'

# - name: Enable NTP
#   check-> timedatectl