---

- name: Check CentOS-Base.repo.backup
  stat: path="/etc/yum.repos.d/CentOS-Base.repo.backup"
  register: bkstat
- name: Backup /etc/yum.repos.d/CentOS-Base.repo
  copy:
    remote_src: true
    src: /etc/yum.repos.d/CentOS-Base.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo.backup
  when: ( not bkstat.stat.exists )

- name: Use new repo setting
  template:
    src: '{{ ansible_distribution }}/CentOS-{{ ansible_distribution_major_version }}.repo'
    dest: /etc/yum.repos.d/CentOS-Base.repo

- name: Update repo cache
  yum:
    list: ansible
    update_cache: yes
    cache_valid_time: 3600
  failed_when: false
  changed_when: false
  ignore_errors: True
